version: '2'
services:
  # it's used for holding all data in one container instead of spreading all data in one machine volumes
  db-data:
    container_name: db-data-mohito
    image: mongo
    entrypoint:
      /bin/true
    volumes:
      - /data/mongodb:/data/db/

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27020:27017
    volumes_from:
      - db-data

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dictionary
    links:
     - mongodb
    volumes:
      - ./server:/usr/src/app
  client:
    build:
      context: ./
      dockerfile: Dockerfile.client
    ports:
      - 3001:3001
    volumes:
      - ./client:/usr/src/app
