version: '3.1'

services:

  production-nginx-container:
    container_name: 'dictify-nginx'
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/dictify-pro.com/fullchain.pem:/etc/letsencrypt/live/dictify-pro.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/dictify-pro.com/privkey.pem:/etc/letsencrypt/live/dictify-pro.com/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt

networks:
  default:
    external:
     - name: dictify-network
